Fix `TypeError`: `PhononBSPlotter.save_plot()` got an unexpected keyword argument `img_format` (#625)
* fix typo

* fix TypeError: PhononBSPlotter.save_plot() got an unexpected keyword argument 'img_format'

following removal in pymatgen, was redundant with filename